// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEW.Models;

namespace SEW.Migrations
{
    [DbContext(typeof(SEWContext))]
    [Migration("20200331091952_RemoveDay")]
    partial class RemoveDay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SEW.Models.Category", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Included")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SEW.Models.Example", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("English")
                        .HasColumnType("TEXT");

                    b.Property<string>("Russian")
                        .HasColumnType("TEXT");

                    b.Property<long>("WordID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WordID");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("SEW.Models.Word", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CanBeDisplayedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("English")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Russian")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcription")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("SEW.Models.Example", b =>
                {
                    b.HasOne("SEW.Models.Word", "Word")
                        .WithMany("Examples")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SEW.Models.Word", b =>
                {
                    b.HasOne("SEW.Models.Category", "Category")
                        .WithMany("Words")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
